---
title: "debug_app"
author: "Nataliya Peshekhodko"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
library(tidyverse)
library(caret)
```


```{r setup, include=FALSE}
data = read_csv('./data/water_potability.csv')
```

```{r}
nrow(data)
sapply(data, function(x) sum(is.na(x)))
```

```{r}
data = na.omit(data)
nrow(data)
#drop_na(data)


trainIndex <- createDataPartition(data$Potability, p = 0.8, 
                                      list = FALSE, 
                                      times = 1)
train_data = data[trainIndex, ]
val_data = data[-trainIndex, ]
```

```{r}


#rf_predictors = input$rf_predictor_selector

rf_predictors = c("ph", "Solids", "Hardness")

train_data$Potability = as.factor(train_data$Potability)

train_control <- trainControl(
            method = "cv",
            #number = as.numeric(input$folds_rf),
            number = 3,
            search = "grid"
        )
rf_model = train(reformulate(rf_predictors, "Potability"),
                 data = train_data,
                 method = "rf",
                 #tuneGrid = data.frame(mtry = c(1:5)),
                 tuneGrid = expand.grid(mtry=c(1:5)),
                 #tuneGrid = expand.grid(mtry=c(as.numeric(input$minMtry):as.numeric(input$maxMtry)) ),
                 #tuneGrid = data.frame(mtry = c(input$minMtry:input$maxMtry)),
                 metric="Accuracy",
                 trControl = train_control,
                 importance = TRUE
                 )


```


```{r}
#str(data)
t = varImp(rf_model, scale = FALSE)

#t2 = importance(rf_model)

#typeof(t2)
```


```{r}
t[[1]]

```


```{r}

vars = c("ph", "Hardness", "Solids")

#lm(reformulate(vars, "Potability"), data=train_data)



train.control = trainControl(method = "cv", 
                              number = 5, 
                              #summaryFunction=mnLogLoss,
                              classProbs = FALSE)

set.seed(83)

train_data$Potability = as.factor(train_data$Potability)
lr_model_1 = train(reformulate(vars, "Potability"), 
                                 data = train_data,
                                 method = "glm", 
                                 family="binomial"
                                 #metric="logLoss",
                                 #trControl = train.control
                                )
summary(lr_model_1)


lr_model_1$results$Accuracy
```

```{r}
glm_predictors = c("ph", "Hardness", "Solids")
glm_model = train(reformulate(glm_predictors, "Potability"), 
                               data = train_data,
                               method = "glm", 
                               family="binomial")
```

```{r}
train_control <- trainControl(
  method = "cv",   
  number = 5
)

rf_model = train(
  Diabetes_binary_transformed ~ HighChol+
                                BMI + 
                                GenHlth+
                                HeartDiseaseorAttack+
                                Age+
                                Income,
  data = select(train_data, -Diabetes_binary),
  method = "rf",
  tuneGrid = data.frame(mtry = c(1:4)), 
  trControl = train_control
)
```


```{r}
vars = c("ph", "Hardness", "Solids")
rf_model = train(
                reformulate(vars, "Potability"),
                data = train_data,
                method = "rf",
                #tuneGrid = data.frame(mtry = c(1:4)),
                #trControl = train_control
            )
```


```{r}


rf_model$results$Accuracy
rf_model$bestTune$mtry
max(rf_model$results$Accuracy)
```

```{r}

split_data <- function(partition, data) {
    
    results <- list()
    trainIndex <- createDataPartition(data$Potability, p = partition, 
                                      list = FALSE, 
                                      times = 1)
    train_data = data[trainIndex, ]
    val_data = data[-trainIndex, ]
    
    results = append(results, train_data)
    results = append(results, val_data)
    
    return (results)
}

```

```{r}
trainIndex <- createDataPartition(data$Potability, p = 0.8, 
                                      list = FALSE, 
                                      times = 1)
train_data = data[trainIndex, ]
val_data = data[-trainIndex, ]

```


```{r}
#t = split_data(0.8, data)

train_data
```


```{r}
typeof(t[[1]])

```

```{r}
data %>%
  filter(Potability == 0) %>%
  nrow

data %>%
  filter(Potability == 1) %>%
  nrow
```


```{r}
data <- data %>%
  mutate(Sulfate_quartiles = case_when(
    Sulfate <= quantile(data$Sulfate)[[1]] ~ "Q1",
    Sulfate > quantile(data$Sulfate)[[1]] & Sulfate <= quantile(data$Sulfate)[[2]] ~ "Q2",
    Sulfate > quantile(data$Sulfate)[[2]] & Sulfate <= quantile(data$Sulfate)[[3]] ~ "Q3",
    Sulfate > quantile(data$Sulfate)[[3]] ~ "Q4"
  )) %>% mutate(Sulfate_quartiles = as.factor(Sulfate_quartiles))
```


```{r}
table(data$Potability)
```


```{r}
ggplot(data, aes(x = Sulfate_quartiles, fill = as.factor(Potability), group = Potability)) +
  geom_bar(position = "stack") +
  labs(
    title = "Number of Cases with Diabetes and Without Diabetes by Income",
    x = "Sulfate quantiles",
    y = "Number of Cases"
  ) +
  scale_fill_manual(
    values = c("0" = "grey", "1" = "red"),
    labels = c("0" = "Not potable", "1" = "Potable")
  ) +
  labs(fill = "Water Potability")
```


```{r}
ggplot(data, aes(x=Sulfate, fill=as.factor(Potability)))+
    geom_density(alpha=.5) +
  scale_fill_manual(
    values = c("0" = "grey", "1" = "red"),
    labels = c("0" = "Not potable", "1" = "Potable")
  ) +
  labs(fill = "Water Potability")
```

```{r}
ggplot(data, aes(x=Hardness, fill=as.factor(Potability)))+
    geom_density(alpha=.5) +
  scale_fill_manual(
    values = c("0" = "grey", "1" = "red"),
    labels = c("0" = "Not potable", "1" = "Potable")
  ) +
  labs(fill = "Water Potability")
```

```{r}
ggplot(data, aes(x=Chloramines, fill=as.factor(Potability)))+
    geom_density(alpha=.5) +
  scale_fill_manual(
    values = c("0" = "grey", "1" = "red"),
    labels = c("0" = "Not potable", "1" = "Potable")
  ) +
  labs(fill = "Water Potability")
```





```{r}
ggplot(data, aes(x = as.factor(Potability), 
                 y = Hardness, group = Potability, fill = as.factor(Potability))) +
 labs(
   title = "Violin Plot of Diabetes Status by BMI",
   x = "Diabetes Status",
   y = "BMI Scale"
 ) +
 geom_violin(trim = FALSE) +
 scale_fill_manual(
   values = c("0" = "grey", "1" = "red"),
   labels = c("0" = "Without Diabetes", "1" = "With Diabetes")
   ) +
 labs(fill = "Diabetes Status")
```


```{r}
str(data)
```

```{r}
corrplot(cor(as.matrix(data)), 
                 type="upper", 
                 tl.pos = "lt")
```
